 
SET WATCOM=C:\DEVEL\WATCOMC
SET INCLUDE=%WATCOM%\H
REM SET DOS_INCLUDE=%WATCOM%\H
REM SET LINUX_INCLUDE=%WATCOM%\LH
SET EDPATH=%WATCOM%\EDDAT
REM SET WIPFC=%WATCOM%\WIPFC
REM SET DOS32A=%WATCOM%
SET PATH=%PATH%;%WATCOM%\BINW
REM SET TMP=D:
REM SET LIB=
REM SET WWINHELP=
